name: Build KernelSU For MI MIX 2s(polaris)

on:
  workflow_dispatch:

jobs:
  KSUForSirius:
    runs-on: ubuntu-latest
    steps:
      - name: Installing Dependencies
        run: |
          sudo apt update -y
          sudo apt-get install -y zip flex bison libncurses-dev gawk  libiberty-dev autoconf kmod bc build-essential gcc libc6 curl libstdc++6 git wget libssl-dev cpio p7zip-full
          sudo apt clean
      - name: Cloning Sources and Toolchain
        run: |
          git clone https://github.com/tosasitill/kernel_xiaomi_sdm845.git --depth=1 --recurse-submodules android_kernel_xiaomi_sdm710_LineageOS
          git clone https://gitlab.com/crdroidandroid/android_prebuilts_clang_host_linux-x86_clang-r445002 --depth=1 --single-branch --no-tags -b 12.0 ~/clang
          git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9 -b android-10.0.0_r47 --depth=1 --single-branch --no-tags ~/aarch64-linux-android-4.9
          git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9 -b android-10.0.0_r47 --depth=1 --single-branch --no-tags ~/arm-linux-androideabi-4.9
      - name: Applying Kernel Patch(LineageOS)
        run: |
           cd android_kernel_xiaomi_sdm710_LineageOS/KernelSU
           wget https://github.com/SakuraNotStupid/KernelSU/commit/7a6f621bfec513732bc97260186a89a79ff66387.patch
           patch -p1 < 7a6f621bfec513732bc97260186a89a79ff66387.patch
           rm -rf *.patch
      - name: Compiling Kernel(LineageOS)
        run: |
          CLANG=~/clang/bin
          GCC32=~/arm-linux-androideabi-4.9/bin
          GCC64=~/aarch64-linux-android-4.9/bin
          PATH=$CLANG:$GCC64:$GCC32:$PATH
          export PATH
          export ARCH=arm64
          export CLANG_TRIPLE=aarch64-linux-gnu
          export CROSS_COMPILE=aarch64-linux-android-
          export CROSS_COMPILE_ARM32=arm-linux-androideabi-
          output_dir=out
          pushd android_kernel_xiaomi_sdm710_LineageOS
          make O="$output_dir" \
                      vendor/xiaomi/mi845_defconfig \
                      vendor/xiaomi/polaris.config
          make -j $(nproc) \
                       O="$output_dir" \
                       CC=clang
          popd
      - name: Packaging the Kernel(LineageOS)
        run: |
          mkdir AnyKernel3
          cp -v android_kernel_xiaomi_sdm710_LineageOS/out/arch/arm64/boot/Image.gz \
                     AnyKernel3/
          pushd AnyKernel3
          7z a -mx9 ../MIMIX2s_KernelSU_LineageOS.zip *
          popd
      - name: Creating Config Info
        run: |
          echo "Device: MI MIX 2s (polaris)
          Build Code: ${{ github.run_number }}
          KernelSU For MI MIX 2s" >> INFO.txt
      - name: Uploading Kernel Package to GH-Release
        uses: ncipollo/release-action@v1.8.6
        with:
          artifacts: MIMIX2s_KernelSU_LineageOS.zip
          name: "MIMIX2s_KernelSU"
          tag: " ${{ github.run_number }}_MIMIX2s_KernelSU"
          bodyFile: "INFO.txt"
          token: ${{ secrets.GITHUB_TOKEN }}
